# -*- coding: utf-8 -*-
"""MyFirstcode_ever

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O7JryhaQHvYpSn8npKKLQ4GH-WxrPlD7
"""

2+1

"2"+"1"

a=5.7

type(a)

a=2
b=1

print(a%b)

a=10

a=a+a

a=a+a

print(a)

type(a)

a='shivi'

type(a)

Taxes = 30000
Salary = 45000

# Tell me what is my savings after taxes?

savings=Salary-Taxes

print(savings)

#situation 2

First_name= "John"

Second_name=" Goodwill"

#John Goodwill is a good man

sentence=First_name + Second_name

print(sentence, a)

# Name

First_name = "Shivi "

Second_name=" Palia"

Age=13

# I am Shivi Palia and my age is 13

sentence=First_name + Second_name

print("I am ",sentence,"and my age is ", Age)

print("I am",First_name+ Second_name,"and my age is",Age)

# This is my first code snippet and I am in class 9th and this is year 2023

# Standard 
# First code snippet 
# year

a= "First code snippet"

b= "9th"

c= 2025

print("This is", a, "and I am in class", b , "and this is year",c-2)

mystring='Hello World'
mystring[8]

